### ISSUE TITLE
Sample script not working in 2.1.3

### ISSUE THREAD

**Issue by davidpelaez** [nats-io/ruby-nats#82]
I run this:

```ruby
require "nats/client"

NATS.start do

  # Simple Subscriber
  NATS.subscribe('foo') { |msg| puts "Msg received : '#{msg}'" }

  # Simple Publisher
  NATS.publish('foo.bar.baz', 'Hello World!')

  # Unsubscribing
  sid = NATS.subscribe('bar') { |msg| puts "Msg received : '#{msg}'" }
  NATS.unsubscribe(sid)

  # Requests
  NATS.request('help') { |response| puts "Got a response: '#{response}'" }

  # Replies
  NATS.subscribe('help') { |msg, reply| NATS.publish(reply, "I'll help!") }

  # Stop using NATS.stop, exits EM loop if NATS.start started the loop
  NATS.stop

end
```

But this happens:
```
dyld: lazy symbol binding failed: Symbol not found: _rb_enable_interrupt
  Referenced from: /Volumes/Low/David/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/eventmachine-0.12.10/rubyeventmachine.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_enable_interrupt
  Referenced from: /Volumes/Low/David/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/eventmachine-0.12.10/rubyeventmachine.bundle
  Expected in: flat namespace

[1]    44007 trace trap  ruby nats.rb
```

Ruby version is `ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]`

I suppose this is related to another gem or something so maybe it's just a matter of updating the manifest of the gem, but I don't know how to solve it and it's the most basic example in the readme so any help is much appreciated :)

**Comment by fbjork** [comment]
+1 also getting this with ruby 2.1.5p273

**Comment by angelbotto** [comment]
:( please reply

**Comment by davidpelaez** [comment]
@fbjork & @angelbotto I think @derekcollison is currently working on the cluster branch and the code there even though not released in the latest version is mostly already available in a beta in Rubygems that works in MRI 2.2.2. The beta isn't exactly as the current head of the cluster branch, but it seems to be working, here's how to use it:

```ruby
gem 'nats', '~> 0.5.0.beta.16', require: 'nats/client'
```

If you want the current head of the repo as of the time of writing ("tested" it and works as well):

```ruby
gem 'nats', 
  git: 'https://github.com/derekcollison/ruby-nats.git', 
  ref: 'be5e96b848d0b8972c6424b2fdbf5f6f777c508b',
  require: 'nats/client'
```

I mean "tested" because I could run the following producer and consumer scripts:

```ruby
require 'rubygems'
require 'bundler/setup'
Bundler.require

NATS.start do
  puts "Connected."
  NATS.subscribe 'help' do |msg, reply| 
    print "."
    NATS.publish reply, msg
  end
end
```

```ruby
require 'rubygems'
require 'bundler/setup'
Bundler.require


NATS.start do
  puts "Connected, sending 50 messages and calculating round trip latency[ms]:"
  50.times do 
    current = (Time.now.to_f*1000).to_i
    NATS.request('help', current) do |response| 
      st = (Time.now.to_f*1000).to_i
      delay = st-response.to_i
      print "#{delay} "
    end
  end
end

```

I'll leave up to @derekcollison to decide if this issue should be closed now or when the release of 0.5 is made.

**Comment by derekcollison** [comment]
Apologies for the slow response, notifications were not making it to my email.

This still an issue? 0.5.0 is released, be happy to take a look.

**Comment by mcqueary** [comment]
Closing due to age. Please comment/reopen if this is still deemed an issue.
